version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    restart: unless-stopped
